### ISSUE TITLE
Billing amounts not taking into account multiple MeterRates

### ISSUE THREAD

**Issue by ChrisRisner** [microsoft/AzureUsageAndBillingPortal#1]
When computing the billed amount for a subscription, only the first MeterRate for each Meter is used.  It's possible there may be multiple MeterRates.  This should be taken into consideration and used to figure out actual pricing.

**Comment by RahulSolanki1487** [comment]
any one working for this issue? i'm getting same error which is causing big issue.

**Comment by ChrisRisner** [comment]
Hello @RahulSolanki1487,

Unfortunately, we've stopped work on this project.  I'd recommend taking a look at the latest Azure Billing API information [here](https://docs.microsoft.com/en-us/azure/billing/billing-usage-rate-card-overview).  You can also take a look at the available [partner solutions](https://docs.microsoft.com/en-us/azure/billing/billing-usage-rate-card-overview#partner-solutions) and the all up documentation on [Azure Billing and Cost Management](https://docs.microsoft.com/en-us/azure/billing/).
