### ISSUE TITLE
It would seem a security risk to bury a password on line 114 of the PS script?

### ISSUE THREAD

**Issue by Mike-Honey** [Microsoft/AzureUsageAndBillingPortal#10]
I noticed that line 114 of the Scripts/CreateAzureServicesScript.ps1 file currently reads:

$passwordADApp = "Password.1%"

I'm no Azure PS guru, but I'm presuming this would create something (an Azure AD app?) using that password.  As it is quite buried, many people will miss it when they review this script, which would presumably create a security risk?

Should that line be moved up to the top of the script, in the parameters section?

**Comment by mustafakasap** [comment]
This line put on the header section with a comment
