### ISSUE TITLE
PS script error: The subscription is not registered for the resource type 'components' in the location 'West US'

### ISSUE THREAD

**Issue by Mike-Honey** [Microsoft/AzureUsageAndBillingPortal#11]
I get the following error running the script: CreateAzureServicesScript.ps1.  What should I do?

New-AzureRmResourceGroupDeployment : 6:18:58 PM - Resource Microsoft.Insights/components 'auiregistrationmangasolutions' failed with 
message '{
  "error": {
    "code": "MissingRegistrationForLocation",
    "message": "The subscription is not registered for the resource type 'components' in the location 'West US'. Please re-register for 
this provider in order to have access to this location."
  }
}'
At line:101 char:1
+ New-AzureRmResourceGroupDeployment -ResourceGroupName $ResouceGroupNa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet

**Comment by russelldyas** [comment]
I had this you can only use App nSights In a Central US region.  If change PowerShell script back to $ResouceGroupLocation = "Central US" it should hopefully work.


From

Russell

**Comment by Mike-Honey** [comment]
Thanks Russell - that got me past that point.
