### ISSUE TITLE
Given the cost impact, should the SQL Edition etc parameters be made more obvious?

### ISSUE THREAD

**Issue by Mike-Honey** [Microsoft/AzureUsageAndBillingPortal#12]
Buried on lines 89 and 91 of the script are these lines:

    sqlEdition = "Standard"
...
    sqlRequestedServiceObjectiveName = "S0";

From what I have observed, these result in a cost impact to anyone running the script, who did not understand the meaning of those lines. A SQL Standard S0 instance is currently around $15/month. 

Should those parameters be made more obvious (e.g. moved to the top of the script) and commented to that effect?

**Comment by mustafakasap** [comment]
Please make a pull request, so we can merge them on your name.

**Comment by Mike-Honey** [comment]
Yeah I looked at that and realised I wouldn't be able to change it with any level of confidence in the result.  Can you do it?

**Comment by russelldyas** [comment]
I can take a look later and see if I can move it or make it more obvious etc.

**Comment by russelldyas** [comment]
My change is now in the master branch which means this issue can be closed
