### ISSUE TITLE
SqlScripts.sql

### ISSUE THREAD

**Issue by tdjastrzebski** [Microsoft/AzureUsageAndBillingPortal#13]
In "SqlScripts.sql" script I suggest changing:
`CREATE PROCEDURE  InsertUsageRecord`
to:
`CREATE PROCEDURE  dbo.InsertUsageRecord`
I am uncertain if that is why this procedure did not create initially.

**Comment by mustafakasap** [comment]
Please make a pull request with the proposal so we can merge your changes with your name
