### ISSUE TITLE
WebJobBillingData.Functions.ProcessQueueMessage() method code defect

### ISSUE THREAD

**Issue by tdjastrzebski** [Microsoft/AzureUsageAndBillingPortal#15]
In case of exception in GetRateCardInfo() method called from WebJobBillingData.Functions.ProcessQueueMessage() returned null value is not handled causing meaningless "Object reference not set" exception.  Suggested change:

```
RateCardPayload rateCardInfo = GetRateCardInfo(rateCardURL, br.OrganizationId);

if (rateCardInfo == null) {
    Console.WriteLine("Problem receiving cost info occured - see log for details.");
    continue;
} else {
    Console.WriteLine("Received cost info: " + rateCardInfo.ToString());
}
```

**Comment by mustafakasap** [comment]
Please make a pull request so we can merge your proposal

**Comment by tdjastrzebski** [comment]
I believe my recent pull request #63 addresses this issue as well as many others.

**Comment by mustafakasap** [comment]
Fixed
