### ISSUE TITLE
Power BI Dashboard Won't Populate

### ISSUE THREAD

**Issue by FrankyFromHR** [Microsoft/AzureUsageAndBillingPortal#18]
The Power BI Dashboard file doesn't appear to be connecting properly to the database. 

After having set the connecting string correctly and seeing data populate into the Advanced Query Editor I am not getting any data in the Dashboard objects, there is also no Fields available to me to select and the refresh button is grayed out. 

I copied the connecting string query into a new Power BI file and I was able to refresh the data and I have Fields to select from. 

Is it possible there is some compatibility issue with the version of Power BI Desktop that was used to create the file initially?

**Comment by tdjastrzebski** [comment]
I have exactly the same problem.

**Comment by KNovotny** [comment]
What worked for me was:
When still in the Edit Queries screen,  in the Query Settings panel, click the "All Properties" link under Properties -> Name -> AzureUsageRecords.  Check " Enable load to report" and "Enable refresh of this query" and press OK.
The data then loaded into the report.  

I still had an issue with the Subscription #, Min Date, Max Data fields.  The solution to these is in this repo under Closed issues.

Hope this works for you!

**Comment by tdjastrzebski** [comment]
It helped. Many thanks :)

**Comment by FrankyFromHR** [comment]
Thanks very much @KNovotny this worked great for me as well, it's probably something that needs to get added to the directions.

**Comment by mustafakasap** [comment]
Please check new end to end video tutorial showing all steps: https://channel9.msdn.com/blogs/Mustafa-Kasap/How-to-Setup-the-Azure-Usage--Billing-Portal

**Comment by mustafakasap** [comment]
Also the document updated according to above suggestions.
