### ISSUE TITLE
Error : The 'ASQLConn-Web.config Connection String' argument cannot be null or empty.

### ISSUE THREAD

**Issue by thavidu** [Microsoft/AzureUsageAndBillingPortal#40]
When following the video and publishing the two webjobs, the output in VS shows the below error:
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.Web.Publishing.targets(4295,5): Error : The 'ASQLConn-Web.config Connection String' argument cannot be null or empty.

You'll notice that in the video, it actually shows the same error too (right beneath the Successfully built message and when it is starting to do its publish step of the process)

Is this harmless? I'm not getting any data in the sql table at the moment so trying to look for the culprit, and am wondering what error is causing it (there could be multiple). 
I'm seeing that 403 forbidden error posted in the other Issue thread by two other people on here, so that could be part of the reason too.
The ARM script didn't give any errors but I noticed the AccountKey= part of my storage string is empty unlike in the video, and I noticed the storage account doesn't have any queues created in it (Not sure which of the components is supposed to create that-- if its from one of the webjobs then I guess its because it is not being published..)

Any help you can give is appreciated!

**Comment by mustafakasap** [comment]
It is not a blocker. If you may check the webjobs from Azure Portal, they should be created succesfuly.

**Comment by nomorechickenstrips** [comment]
It is still an issue and should be re-opened and addressed properly.

https://stackoverflow.com/questions/28391460/how-do-i-setup-connection-strings-for-a-webjob-project
