### ISSUE TITLE
"Invalid object name 'dbo.PerUserTokenCaches'."

### ISSUE THREAD

**Issue by franlix** [Microsoft/AzureUsageAndBillingPortal#43]
In "SqlScripts.sql" there isn't "dbo.PerUserTokenCaches".
Can you update the script?
Thanks
F

**Comment by mustafakasap** [comment]
after you setup web apps, you need to launch the web app at least once (i.e. try to open the registration page and try login...) MVA web app will automatically create its own DB tables, one of whic is the you mentioned above. Video shows all these steps in order, even opening the web page.
