### ISSUE TITLE
Microsoft.Insight breaking change.

### ISSUE THREAD

**Issue by dawidgrey** [Microsoft/AzureUsageAndBillingPortal#45]
The template needs an update according to this:https://azure.microsoft.com/en-us/updates/application-insights-general-availability-in-additional-regions-and-resource-location-update-east-us-south-central-us-west-europe-and-north-europe/
since 22 Nov.

**Comment by lettucebo** [comment]
agree, having this issue, can't use template right now

**Comment by mathieu-benoit** [comment]
Hi @dawidgrey and @lettucebo, good catch! I submitted one PR to fix that #46.

**Comment by mustafakasap** [comment]
PR merged and issue closed. Thanks for all your support.
