### ISSUE TITLE
Problem in DataGenStatus

### ISSUE THREAD

**Issue by bokebasa** [Microsoft/AzureUsageAndBillingPortal#47]
I have completed all the process without problems but at the end in the dashboard website the data generation status is always Pending as you can see in the following picture because of this there are tables of power bi that are empty like AzureUsageRecords, ReportRequests and Reports. Does anyone know why this problem is caused? Thank you very much and I hope your answer.
![image](https://cloud.githubusercontent.com/assets/24693826/21519755/e39a2792-ccef-11e6-8f51-12948f999a7a.png)

**Comment by FBoucher** [comment]
What's the type of your subscription? (ex: Pay as you go, csp. ect.)

**Comment by bokebasa** [comment]
I finally solve the problem http://stackoverflow.com/questions/27332324/no-route-registered-for-webjob the schedule was not working, to solve i deleted the job and then re-published it.
