### ISSUE TITLE
AADSTS70001 when trying to register another subscriptio

### ISSUE THREAD

**Issue by henrikm** [Microsoft/AzureUsageAndBillingPortal#53]
Situation:
Deployed AUBI Portal on a MSDN Subscription. Portal works fine. Can register the subscription to AUBI that is also used for the hosting of the portal itself.

Error:
When trying to register another subscription I get AADSTS70001. This is a pay as you go subscription in another tenant. Also I can not register another subscription from an EA account. 

![image](https://cloud.githubusercontent.com/assets/3972559/22327956/19e72576-e3ba-11e6-90b5-35d0197169e7.png)

**Comment by FBoucher** [comment]
EA accounts are not supported yet.

**Comment by henrikm** [comment]
And another Pay as you Go subscriptions from another tenant?



Am 26.01.2017 11:36 vorm. schrieb "FBoucher" <notifications@github.com>:

**Comment by harleenkohli** [comment]
@henrikm - https://github.com/Microsoft/peek/ should help. This solution caters to EA scenario by connecting Azure EA APIs.
