### ISSUE TITLE
Unable to add subscription from a Multi Organization Account

### ISSUE THREAD

**Issue by 5nowx** [Microsoft/AzureUsageAndBillingPortal#54]
Hello.

When i log in with my work account, i cant add a subscription, I have multiple organizations and you chose from one of them. Here i see the yellow error:

![screenshot 2017-01-26 at 11 16 19 am](https://cloud.githubusercontent.com/assets/12454521/22334280/ebf06f0c-e3b8-11e6-86b4-9ba03d097f52.png)

i cant click in any part of the yellow box, and no other menu is displayed

**Comment by 5nowx** [comment]
This is in IE/Chrome/Firefox

**Comment by rzand** [comment]
I have the same issue. Has anybody found a solution or a workaround for this? Thanks.

**Comment by 5nowx** [comment]
What I did was create an account user@specifictenant.onmicrosoft.com and use that to register the application

**Comment by mustafakasap** [comment]
you should provide a subscription name without @ symbol. In the text box there is a help popup link. Please check that information.
