### ISSUE TITLE
Error : An error occurred while creating the WebJob schedule: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by 5nowx** [Microsoft/AzureUsageAndBillingPortal#55]
Hello
i get this error when trying to publish WebJobUsageDaily

It publish its corrctly but, when starts creating the Scheduler Job it gives me:

`\AzureUsageAndBillingPortal-master\packages\Microsoft.Web.WebJobs.Publish.1.0.9\tools\webjobs.console.targets(110,5): Error : An error occurred while creating the WebJob schedule: Object reference not set to an instance of an object.`

**Comment by tdjastrzebski** [comment]
Hi, my pull request #63 addresses this issue in a way WebJob schedule is defined within WebJob  itself (App.config) or via hosting App Service settings. That is, no separate schedule/external trigger is needed.

**Comment by 5nowx** [comment]
thanks, I did a re-Launching in march, from zero, and all worked fine, Closing this one.
