### ISSUE TITLE
CreateAzureServicesScript.ps1 failing - workaround

### ISSUE THREAD

**Issue by djhmateer** [Microsoft/AzureUsageAndBillingPortal#57]
I found that I had to make the following changes around line 100 to get the script to run. Also found that the script didn't display my access token (I got from Azure portal)

#web1SiteName = $Web1SiteName;
registrationWebSiteName = $Web1SiteName;

#web2SiteName = $Web2SiteName;
dashboardWebSiteName = $Web2SiteName;

**Comment by 5nowx** [comment]
Found the same problem can confirm.

**Comment by mustafakasap** [comment]
It is fixed in the new PS1 file
