### ISSUE TITLE
query editor empty when refresh preview

### ISSUE THREAD

**Issue by percoclap** [Microsoft/AzureUsageAndBillingPortal#62]
Hi all
I done all the steps mentionned in the channel9 setup video. and just after importing the .pbix file and set credentials + connection string, the table is empty when I click on REFRESH PREVIEWW button. do you see what is going on ? :( 

when I check the SQL DB through MGMT studio all tables of the database are empty, is it normal ? so you see what is happening ? if you have an idea I would really appreciate ! thanks a lot for your feedback

**Comment by mustafakasap** [comment]
Goto WebApp on AzurePortal. In the Dashboard blade (page) of the dashboard web app, explore the webjobs that you published under this webapp. You will see LOG button. Follow that feature to see the status of Web jobs... if they are running or failure. If there is no data in the SQL either webjob failed for some reason or still processing
