### ISSUE TITLE
AADSTS90002 when trying to register a subscription

### ISSUE THREAD

**Issue by Neorick25** [Microsoft/AzureUsageAndBillingPortal#64]
The subscription where I publish the AUI App it's registered ok, but if I try to add another subscription I get the error:

Correlation ID: 279aac69-2cb7-47c4-9031-7d54da9ca3bb 
Timestamp: 2017-04-12 17:36:01Z 
AADSTS90002: Requested tenant identifier '00000000-0000-0000-0000-000000000000' is not valid. Tenant identifiers may not be an empty GUID. 

Regards.

**Comment by adamcosby85** [comment]
I too am getting this exact issue - did you manage to solve it?

**Comment by mustafakasap** [comment]
already answered in https://github.com/Microsoft/AzureUsageAndBillingPortal/issues/53
