### ISSUE TITLE
Unable to create SQL server

### ISSUE THREAD

**Issue by djhalibut** [Microsoft/AzureUsageAndBillingPortal#65]
Hi,

When I am running the script “CreateAzureServicesScript.ps1” I am getting following error message:

`New-AzureRmResourceGroupDeployment : 15:18:39 - Resource Microsoft.Sql/servers 'auisqlsr5' failed with message {
  "code": "45122",
  "message": "''",
  "target": null,
  "details": [
    {
      "code": "45122",
      "message": "''",
      "target": null,
      "severity": "16"
    }
  ],
  "innererror": []
}
At D:\AzureUsageAndBillingPortal-master\Scripts\CreateAzureServicesScript.ps1:107 char:1
+ New-AzureRmResourceGroupDeployment -ResourceGroupName $ResourceGroupN ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet`

I was trying to change the Resource Group location but the issue still persist.

**Comment by djerro123** [comment]
Same issue here; you'll need to add an sql-db yourself, keeping the same values as the script outputs (keeping the samen server name, db name, etc). Everything should work after that.

Reason is (I think, not confirmed) that we are using a free trial subscription..

**Comment by djhalibut** [comment]
I am not using trial.. I'll try to add the database manually. Thanks.

**Comment by tylerd** [comment]
If anyone is still having this issue, you can try changing the Azure DB Version from 2.0 to 12.0

Line 42 of [CreateAzureServicesScript.ps1](https://github.com/Microsoft/AzureUsageAndBillingPortal/blob/master/Scripts/CreateAzureServicesScript.ps1)

`$SQLServerVersion = "12.0"`

**Comment by mustafakasap** [comment]
Thanks @tylerd issue fixed.
