### ISSUE TITLE
Historical data isn't loaded after a repaired 400 bad request error

### ISSUE THREAD

**Issue by djerro123** [Microsoft/AzureUsageAndBillingPortal#66]
The webjob BillingData is not loading the historical data once you've (unsuccessfully) had it ran. Is there a way to reset aside from starting all over?

Thanks!

**Comment by mustafakasap** [comment]
In the dashboard web app, there is an option to regenerate - rerun web jobs... Or you can manually re-trigger webjob calls through azure management portal.
