### ISSUE TITLE
Power BI

### ISSUE THREAD

**Issue by KNovotny** [Microsoft/AzureUsageAndBillingPortal#7]
Subscription #, Min Date, Max Date do not render.

**Comment by mustafakasap** [comment]
These custom autocalc fields can be updated by writing simple Excel like functions: 

Max Date = MAX(AzureUsageRecords[usageEndTime])
Min Date = MIN(AzureUsageRecords[usageStartTime])
# Subscriptions = DISTCOUNT(AzureUsageRecords[subscriptionId])

In few days we will publish a video to show end to end installation of the portal with all these steps.

**Comment by KNovotny** [comment]
Awesome!  Thanks so much.  I followed the instructions and have the entire solution working except for that; I was fairly sure that's all that was needed, but wanted to be sure to capture any issues.  Looking forward to the videos.

**Comment by KNovotny** [comment]
Add new measure column:
Max Date = MAX(AzureUsageRecords[usageEndTime])
Min Date = MIN(AzureUsageRecords[usageStartTime])
# Subscriptions = DISTINCTCOUNT(AzureUsageRecords[subscriptionId])

**Comment by tdjastrzebski** [comment]
One correction. The last one should be:  # Subscriptions
(space after #)
