### ISSUE TITLE
Delete existing record is not working in "InsertIntoSqlDbAsync" method.

### ISSUE THREAD

**Issue by RahulSolanki1487** [Microsoft/AzureUsageAndBillingPortal#83]
delete existing record is not working in "InsertIntoSqlDbAsync" method when you supply date range. if pass only 1 day it's working. due to this it'll add new record every time you refresh data for same date and cost will calculated multiple time. so if your actual cost is $600 and you refreshed it 2 times after initial load cost will display $1800 which 3 times[1 initial load +  2 time refresh].

**Comment by RahulSolanki1487** [comment]
i resolved this issue already for my solution. delete query is wrong in this method . change delete query to this : "delete from dbo.AzureUsageRecords with(repeatableread, rowlock) where SubscriptionId = @subscriptionId and (UsageStartTime >= @usageStartTime and UsageEndTime <= @usageEndTime)" where code will look for date range between start and end. this will resolve issue. after replacing this you may get another issue of transaction when code try to delete record more than 20000 rows. it'll fail. so you may need to scale up azure sql db or delete those rows before you reload data using sql query.

**Comment by mustafakasap** [comment]
@RahulSolanki1487  you may make a pull request to have this one fixed.
